### ISSUE TITLE
Readme: How does this project compare to polars

### ISSUE THREAD

**Issue by mbyt** [Rusty-Gopher/randas#1]
That's an interesting project!

In the readme, I tried to understand the difference to [pola-rs/polars: Dataframes powered by a multithreaded, vectorized query engine, written in Rust](https://github.com/pola-rs/polars), which is also a DataFrame library written in Rust, it is based on [Apache Arrow | Apache Arrow](https://arrow.apache.org/). But I didn't find a reference. Is it possible to add a short comparision?

**Comment by Rusty-Gopher** [comment]
Thanks @mbyt 

Sure here are the major differences:

1. Polars usea apache Arrow arrarys, my library uses hashmap which is configured using internal dataframe values in enum
2. Polars has no indexing, My library has automatic index generation, not user manipulated.

Overall, its a hobby project, which came from the idea that how can i learn rust, and also implement something to convert my in house scripting from python. The answer was converting pandas library in rust, and now i can use this.

In terms of performance vs pandas, i had good performance improvements in reading  and writing excel sheets.

If there is something you want to see in the library, you can add this as a feature request.
